apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-wfmy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-wfmy
    app.kubernetes.io/part-of: tkrw-pr712-0075-0074-app
  name: devfile-sample-wfmy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-wfmy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-wfmy
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0074-tenant/tkrw-pr712-0075-0074-app/devfile-sample-wfmy@sha256:e14c8c76acd0b2fb5e4c1e202cfa104b3361e1b188111480ca4bc44539f93774
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
